docker_image: "quay.io/condaforge/linux-anvil-cos7-x86_64:latest"
env_name: "2023-1.0-py310-n2acc-ml-ops"
conda_env_file: "env-py310.yml"
conda_binary: "mamba"
python_version: "3.10"
pkg_name: ""
pkg_version: ""
extra_packages: "mamba"
channels: "-c conda-forge"
